#!/bin/sh
# --no-defaults must be the first argument; insert --skip-ssl right after it
case "$1" in
  --no-defaults|--defaults-file=*|--defaults-extra-file=*)
    first="$1"; shift
    exec /usr/bin/mariadb "$first" --skip-ssl "$@"
    ;;
  *)
    exec /usr/bin/mariadb --skip-ssl "$@"
    ;;
esac
