server {
    listen 80;
    server_name omakeikka.local.dev;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name omakeikka.local.dev;
    root /var/www/html/web;

    ssl_certificate /etc/nginx/ssl/localdev.crt;
    ssl_certificate_key /etc/nginx/ssl/localdev.key;

    client_max_body_size 15m;

    index index.php;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass php:9000;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $document_root;
    }

    location ^~ /app/uploads/ {
        alias /var/www/html/web/app/uploads/;
        access_log off;
        expires 30d;
        add_header Cache-Control "public";
        try_files $uri =404;
    }
}
